# Generated by Django 3.0.1 on 2019-12-21 06:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regusers',
            options={'verbose_name': 'Registered Users', 'verbose_name_plural': 'Registered Users'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Users', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='regusers',
            name='phone',
        ),
        migrations.AddField(
            model_name='clinic',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+999999999999', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regusers',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+999999999999', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='regusers',
            name='personnumber',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='users',
            name='personnumber',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
